---
- name: Deploy containers
  hosts: appsrvgrp         // Группа, которую нужно будет прописать в Inventory
  become: yes

  tasks:
    - name: Include vars   // Подтягиваем переменные
      include_vars:
        dir: vars

    - name: Create remote temp dir  // Создать папку для временных файлов на целевой машине
      file:
        path: /tmp/votingapp
        state: directory

    - name: Copy Docker Compose files  // Приземлить шаблон и скопировать его на целевую машину
      template:
        src: templates/docker-compose.j2
        dest: /tmp/votingapp/docker-compose.yml
        force: yes

    - name: Stop all docker containers  // Останавливаем все докер-контейнеры
      shell:
        cmd: docker stop $(docker ps -q)
      ignore_errors: true
      tags:
        - docker-cleanup

    - name: Remove all unused and dangling docker images
      shell:
        cmd: docker system prune --all --force
      tags:
        - docker-cleanup

    - name: Setup with docker-compose
      shell:
        cmd: docker-compose up -d
        chdir: /tmp/votingapp
      register: contdeploy
      tags:
        - container-setup

    - name: Display result
      debug:
        msg: "Log from docker-compose: \n {{ contdeploy.stdout }}\n"
